PKGNAME = ccusage-statusline-rs
VERSION = $(shell grep -Po '^version = "\K[^"]+' Cargo.toml)
TARBALL = $(PKGNAME)-$(VERSION).tar.xz

DOCKER ?= $(shell command -v podman || command -v docker)
DEB_ARCH ?= amd64
DEB_REVISION ?= 1
DEB_VERSION = $(VERSION)-$(DEB_REVISION)
RUST_ARCH = $(if $(filter arm64,$(DEB_ARCH)),aarch64,x86_64)
BINARY = dist/$(PKGNAME)-linux-$(RUST_ARCH)
DEB = $(PKGNAME)_$(DEB_VERSION)_$(DEB_ARCH).deb
STAGE = target/package.tmp

.PHONY: all tarball package install clean screenshot deb deb-all

all: package

tarball:
	git archive --format=tar --prefix=$(PKGNAME)-$(VERSION)/ HEAD > $(PKGNAME)-$(VERSION).tar
	@if [ -z "$$(git ls-files Cargo.lock)" ]; then \
		echo "Cargo.lock untracked; generating and injecting..."; \
		cargo generate-lockfile; \
		tar -rf $(PKGNAME)-$(VERSION).tar --transform='s,^,$(PKGNAME)-$(VERSION)/,' Cargo.lock; \
	fi
	xz -c $(PKGNAME)-$(VERSION).tar > $(TARBALL)
	@rm -f $(PKGNAME)-$(VERSION).tar
	@echo "Created $(TARBALL)"

package: tarball
	@echo "Preparing PKGBUILD for local build..."
	@cp PKGBUILD PKGBUILD.bak
	@sed -i 's|source=("https://github.com/ticpu/$$pkgname/releases/download/v$$pkgver/$$pkgname-$$pkgver.tar.xz")|source=("$$pkgname-$$pkgver.tar.xz")|' PKGBUILD
	makepkg -si --noconfirm
	@mv PKGBUILD.bak PKGBUILD

install:
	makepkg -si --noconfirm

# Same command the release workflow runs, so a .deb built here comes off the
# binary that ships. One pass emits every architecture, and in CI the files
# already exist from the workflow's own build step.
dist/$(PKGNAME)-linux-x86_64 dist/$(PKGNAME)-linux-aarch64 &: Containerfile Cargo.toml $(wildcard src/*.rs)
	DOCKER_BUILDKIT=1 $(DOCKER) build -f Containerfile --output type=local,dest=dist .

deb: $(DEB)

deb-all:
	$(MAKE) deb DEB_ARCH=amd64
	$(MAKE) deb DEB_ARCH=arm64

# A version bump otherwise leaves the previous version's .deb behind for a
# release job to pick up alongside the current one.
$(DEB): $(BINARY) packaging/debian/control LICENSE README.md
	@for f in $(PKGNAME)_*.deb; do \
		[ -e "$$f" ] || continue; \
		case "$$f" in \
			$(PKGNAME)_$(DEB_VERSION)_amd64.deb|$(PKGNAME)_$(DEB_VERSION)_arm64.deb) ;; \
			*) rm -f "$$f"; echo "removed stale $$f" ;; \
		esac; \
	done
	@if readelf -l "$(BINARY)" | grep -q INTERP; then \
		echo "$(BINARY) is dynamically linked; the packaged binary must be static musl" >&2; \
		exit 1; \
	fi
	@needed=$$(readelf -d "$(BINARY)" | sed -n 's/.*NEEDED.*\[\(.*\)\]/\1/p'); \
	if [ -n "$$needed" ]; then \
		echo "$(BINARY) needs shared libraries this recipe cannot map to packages:" >&2; \
		echo "$$needed" >&2; \
		echo "declare them in packaging/debian/control before packaging again" >&2; \
		exit 1; \
	fi
	rm -rf "$(STAGE)"
	install -D -m 755 -T "$(BINARY)" "$(STAGE)/usr/bin/$(PKGNAME)"
	install -D -m 644 -T LICENSE "$(STAGE)/usr/share/doc/$(PKGNAME)/copyright"
	install -D -m 644 -T README.md "$(STAGE)/usr/share/doc/$(PKGNAME)/README.md"
	mkdir -p "$(STAGE)/DEBIAN"
	sed -e 's/@VERSION@/$(DEB_VERSION)/' -e 's/@ARCH@/$(DEB_ARCH)/' \
		packaging/debian/control > "$(STAGE)/DEBIAN/control"
	chmod 644 "$(STAGE)/DEBIAN/control"
	@if grep -n '@[A-Z_]\+@' "$(STAGE)/DEBIAN/control"; then \
		echo "unsubstituted placeholders remain in the control file" >&2; exit 1; \
	fi
	@if grep -rq "$$PWD" "$(STAGE)"; then \
		echo "package contains the build path ($$PWD)" >&2; exit 1; \
	fi
	dpkg-deb --build --root-owner-group "$(STAGE)" "$@"
	rm -rf "$(STAGE)"

# Reads a captured statusline on stdin, ANSI codes intact:
#   <statusline invocation> | make screenshot
# Not generated by running the tool here: `test` has no context window and falls
# back to counting the whole transcript, saturating the percentage at 100%, and
# the API-dependent elements only appear against a live endpoint.
screenshot:
	python3 docs/tools/ansi2svg.py > docs/images/status-line.svg
	@echo "Wrote docs/images/status-line.svg"

clean:
	rm -f $(TARBALL)
	rm -rf $(PKGNAME)-$(VERSION)/
	rm -rf pkg/
	rm -f *.pkg.tar.zst
	rm -f PKGBUILD.bak
	rm -rf dist/
	rm -f $(PKGNAME)_*.deb