name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tarball
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          git archive --format=tar --prefix=ccusage-statusline-rs-${VERSION}/ HEAD | xz -c > ccusage-statusline-rs-${VERSION}.tar.xz

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ccusage-statusline-rs-*.tar.xz
          draft: false
          prerelease: false
          generate_release_notes: true

  build-binaries:
    name: Build Binaries
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ccusage-statusline-rs-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: ccusage-statusline-rs-linux-aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          PKG_CONFIG_ALLOW_CROSS: 1

      - name: Strip binary
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            aarch64-linux-gnu-strip target/${{ matrix.target }}/release/ccusage-statusline-rs
          else
            strip target/${{ matrix.target }}/release/ccusage-statusline-rs
          fi

      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/ccusage-statusline-rs ${{ matrix.artifact_name }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_name }}